version: "3"

volumes:
  database:

services:
  database:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=maxinum_test
    volumes:
      - database:/var/lib/postgresql/data
